# Generated by Django 6.0 on 2025-12-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
    ]
